language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: 
  - pip install git+https://github.com/lbusoni/pymba
  - pip install .
  - pip install coveralls
script:
  - pytest
  - coverage run --source=pysilico_server setup.py test
  - coverage report -m
after_success:
  - coveralls
